# Generated by Django 4.2.5 on 2023-10-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
