# Generated by Django 4.2.5 on 2023-10-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_alter_formdata_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='time',
            new_name='date',
        ),
    ]
