# Generated by Django 4.2.5 on 2023-10-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_rename_time_formdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='address',
        ),
        migrations.AddField(
            model_name='formdata',
            name='district',
            field=models.CharField(default='default_district', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formdata',
            name='province',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
            ),

    ]
