# Generated by Django 4.2.5 on 2023-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_formdata_address_formdata_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='province',
            field=models.CharField(max_length=100),
        ),
    ]
