# Generated by Django 4.2.5 on 2023-10-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_formdata_district_alter_formdata_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
