# Generated by Django 4.2.5 on 2023-10-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_province_alter_formdata_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
