# Generated by Django 4.2.5 on 2023-10-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_formdata_province_delete_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='province',
            field=models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh')], max_length=100),
        ),
    ]
