# Generated by Django 4.2.5 on 2023-10-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_formdata_district_alter_formdata_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='province',
            field=models.CharField(choices=[('Koshi', 'Koshi'), ('Madhesh', 'Madhesh'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpaschim', 'Sudurpaschim')], max_length=100),
        ),
    ]
