# Generated by Django 4.2.5 on 2023-10-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_formdata_district_alter_formdata_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
