# Generated by Django 4.2.5 on 2023-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_formdata_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formdata',
            name='purpose',
            field=models.CharField(default='Personal', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
