# Generated by Django 4.2.5 on 2023-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_formdata_has_vehicle_formdata_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='has_vehicle',
            field=models.BooleanField(default=True),
        ),
    ]
