# Generated by Django 4.2.5 on 2023-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_formdata_has_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='status',
            field=models.CharField(choices=[('Gate Pass', 'Gate Pass'), ('Entered', 'Entered'), ('Exited', 'Exited')], default='Gate Pass', max_length=20),
        ),
    ]
