# Generated by Django 4.2.5 on 2023-10-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_formdata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='status',
        ),
        migrations.AddField(
            model_name='formdata',
            name='entry_button',
            field=models.CharField(default='Entry', max_length=20),
        ),
        migrations.AddField(
            model_name='formdata',
            name='exit_button',
            field=models.CharField(default='Exit', max_length=20),
        ),
    ]
