# Generated by Django 4.2.5 on 2023-10-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_remove_formdata_status_formdata_entry_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='youtube',
        ),
    ]
