# Generated by Django 4.2.5 on 2023-10-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_remove_trainer_facebook_remove_trainer_pinterest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='img',
        ),
        migrations.RemoveField(
            model_name='trainerachivement',
            name='img',
        ),
    ]
