# Generated by Django 4.2.5 on 2023-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_trainer_img_remove_trainerachivement_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='group',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AddField(
            model_name='formdata',
            name='status',
            field=models.CharField(choices=[('Gate Pass', 'Gate Pass'), ('Entered', 'Entered'), ('Exited', 'Exited')], default='Gate Pass', max_length=20),
        ),
    ]
