# Generated by Django 4.2.5 on 2023-10-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_formdata_group_formdata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='group',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='status',
        ),
    ]
