# Generated by Django 4.2.5 on 2023-10-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_formdata_group_remove_formdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='current_status',
            field=models.CharField(choices=[('Gate Pass', 'Gate Pass'), ('Entered', 'Entered'), ('Exited', 'Exited')], default='Gate Pass', max_length=20),
            preserve_default=False,
        ),
    ]
