# Generated by Django 4.2.5 on 2023-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_formdata_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Gate Pass', 'Gate Pass'), ('Entered', 'Entered'), ('Exited', 'Exited')], max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='entry_button',
            field=models.CharField(blank=True, default='Entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='exit_button',
            field=models.CharField(blank=True, default='Exit', max_length=20),
        ),
    ]
