# Generated by Django 4.2.5 on 2023-10-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_formdata_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Gate Pass', 'Gate Pass'), ('Entered', 'Entered'), ('Exited', 'Exited')], default='Gate Pass', max_length=20),
        ),
    ]
