# Generated by Django 4.2.5 on 2023-10-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_formdata_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='group',
            field=models.CharField(blank=True, default='User', max_length=20),
        ),
    ]
