# Generated by Django 4.2.5 on 2023-10-17 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_formdata_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
