# Generated by Django 4.2.5 on 2023-10-17 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_formdata_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
