# Generated by Django 4.2.5 on 2023-10-17 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_alter_formdata_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 7, 48, 51, 53917, tzinfo=datetime.timezone.utc)),
        ),
    ]
