# Generated by Django 4.2.5 on 2023-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_alter_formdata_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(),
        ),
    ]
