# Generated by Django 4.2.5 on 2023-10-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_alter_formdata_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(default=None),
        ),
    ]
