# Generated by Django 4.2.5 on 2023-10-17 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_remove_formdata_date_of_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formdata',
            name='date_of_exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
