# Generated by Django 4.2.5 on 2023-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_formdata_date_of_entry_formdata_date_of_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
