# Generated by Django 4.2.5 on 2023-10-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_alter_formdata_date_of_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='district',
        ),
    ]
