# Generated by Django 4.2.5 on 2023-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_remove_formdata_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
