# Generated by Django 4.2.5 on 2023-10-30 11:26

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_formdata_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
