# Generated by Django 4.2.5 on 2023-10-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_formdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date',
            field=models.DateField(),
        ),
    ]
