# Generated by Django 4.2.5 on 2023-10-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_alter_formdata_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
