# Generated by Django 4.2.5 on 2023-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_alter_formdata_date_alter_formdata_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='district',
            field=models.CharField(choices=[('Koshi', [('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Khotang', 'Khotang'), ('Morang', 'Morang'), ('Okhaldhunga', 'Okhaldhunga'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur')]), ('Madhesh', [('Bara', 'Bara'), ('Dhanusa', 'Dhanusa'), ('Mahottari', 'Mahottari'), ('Parsa', 'Parsa'), ('Rautahat', 'Rautahat'), ('Saptari', 'Saptari'), ('Sarlahi', 'Sarlahi'), ('Siraha', 'Siraha')]), ('Bagmati', [('Bhaktapur', 'Bhaktapur'), ('Chitwan', 'Chitwan'), ('Dhading', 'Dhading'), ('Dolakha', 'Dolakha'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Lalitpur', 'Lalitpur'), ('Makwanpur', 'Makwanpur'), ('Nuwakot', 'Nuwakot'), ('Ramechhap', 'Ramechhap'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Sindhupalchok', 'Sindhupalchok')]), ('Gandaki', [('Gorkha', 'Gorkha'), ('Kaski', 'Kaski'), ('Lamjung', 'Lamjung'), ('Manang', 'Manang'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Nawalpur', 'Nawalpur'), ('Parbat', 'Parbat'), ('Syangja', 'Syangja'), ('Tanahun', 'Tanahun')]), ('Lumbini', [('Arghakhanchi', 'Arghakhanchi'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Nawalparasi East', 'Nawalparasi East'), ('Palpa', 'Palpa'), ('Rupandehi', 'Rupandehi'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya')]), ('Karnali', [('Dolpa', 'Dolpa'), ('Humla', 'Humla'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Nawalparasi West', 'Nawalparasi West'), ('Salyan', 'Salyan')]), ('Sudurpaschim', [('Achham', 'Achham'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Baitadi', 'Baitadi'), ('Dadeldhura', 'Dadeldhura'), ('Darchula', 'Darchula'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')])], max_length=100),
        ),
    ]
