# Generated by Django 4.2.5 on 2023-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_alter_formdata_district_alter_formdata_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(default='023456', max_length=20),
        ),
    ]
