# Generated by Django 4.2.5 on 2023-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_alter_formdata_district_alter_formdata_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='duration_of_stay',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
