# Generated by Django 4.2.5 on 2023-11-06 14:30

from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_formdata_duration_of_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date',
            field=nepali_datetime_field.models.NepaliDateField(blank=True, null=True),
        ),
    ]
