# Generated by Django 4.2.5 on 2023-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_alter_formdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
