# Generated by Django 4.2.5 on 2023-12-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_alter_formdata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
    ]
