# Generated by Django 4.2.5 on 2023-12-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_appsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Gate Pass', 'Gate Pass'), ('Entered', 'Entered'), ('Exited', 'Exited')], default='Gate Pass', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='entry_button',
            field=models.CharField(blank=True, default='Entry', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='exit_button',
            field=models.CharField(blank=True, default='Exit', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='group',
            field=models.CharField(blank=True, default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='id_number',
            field=models.CharField(default='023456', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(default='defName', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
