# Generated by Django 4.2.5 on 2023-12-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_alter_formdata_district_alter_formdata_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100)),
                ('item_status', models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('damaged', 'Damaged')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('consumable', 'Consumable'), ('non_consumable', 'Non-Consumable')], max_length=20)),
                ('entry_details', models.ManyToManyField(to='main.entrydetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='assignsubscriber',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='assignsubscriber',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.RemoveField(
            model_name='notiftrainerstatus',
            name='notif',
        ),
        migrations.RemoveField(
            model_name='notiftrainerstatus',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='notifuserstatus',
            name='notif',
        ),
        migrations.RemoveField(
            model_name='notifuserstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='read_by_trainer',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='read_by_user',
        ),
        migrations.RemoveField(
            model_name='plandiscount',
            name='subplan',
        ),
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainerachivement',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainermsg',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainermsg',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainersalary',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_for_trainer',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_for_user',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_from_trainer',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_from_user',
        ),
        migrations.DeleteModel(
            name='AssignSubscriber',
        ),
        migrations.DeleteModel(
            name='NotifTrainerStatus',
        ),
        migrations.DeleteModel(
            name='NotifUserStatus',
        ),
        migrations.DeleteModel(
            name='Notify',
        ),
        migrations.DeleteModel(
            name='PlanDiscount',
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
        migrations.DeleteModel(
            name='SubPlanFeature',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
        migrations.DeleteModel(
            name='TrainerAchivement',
        ),
        migrations.DeleteModel(
            name='TrainerMsg',
        ),
        migrations.DeleteModel(
            name='TrainerNotification',
        ),
        migrations.DeleteModel(
            name='TrainerSalary',
        ),
        migrations.DeleteModel(
            name='TrainerSubscriberReport',
        ),
    ]
