# Generated by Django 4.2.5 on 2024-01-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_entrydetail_item_remove_assignsubscriber_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='entry_details',
        ),
        migrations.DeleteModel(
            name='EntryDetail',
        ),
        migrations.AddField(
            model_name='item',
            name='entry_details',
            field=models.JSONField(default=list),
        ),
    ]
