# Generated by Django 4.2.5 on 2024-01-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_remove_item_entry_details_delete_entrydetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='entry_details',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='assignedOffice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('operational', 'Operational'), ('damaged', 'Damaged'), ('maintained', 'Maintained')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='consumable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='damagedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='maintainedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='officeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='returnedOffice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='storeDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
