# Generated by Django 4.2.5 on 2024-01-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_alter_item_description_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assignedOffice',
            field=models.TextField(blank=True, default='Store'),
        ),
    ]
