# Generated by Django 4.2.5 on 2024-01-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_alter_item_assignedoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='assignedOffice',
            field=models.TextField(blank=True, default='STORE'),
        ),
    ]
