# Generated by Django 4.2.5 on 2024-01-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.TextField(blank=True, default='Damaged'),
        ),
    ]
