# Generated by Django 4.2.5 on 2024-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_item_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='remarks',
            field=models.CharField(blank=True, default='Damaged'),
        ),
    ]
