# Generated by Django 4.2.5 on 2024-01-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_alter_item_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
