# Generated by Django 4.2.5 on 2024-01-15 15:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_notification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AddField(
            model_name='item',
            name='additem_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.item_photo_upload_path),
        ),
        migrations.AddField(
            model_name='item',
            name='changestatus_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.changestatus_photo_upload_path),
        ),
        migrations.AddField(
            model_name='item',
            name='returnitem_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.returnitem_photo_upload_path),
        ),
    ]
