# Generated by Django 4.2.5 on 2024-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_remove_item_photo_item_additem_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assign_item', 'Assign Item'), ('return_item', 'Return Item'), ('change_status', 'Change Status'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
