# Generated by Django 4.2.5 on 2024-01-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_notification_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
