# Generated by Django 4.2.5 on 2024-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_delete_formdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consumable',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('non_consumable', 'Non-Consumable')], default='consumable', max_length=20),
        ),
    ]
