# Generated by Django 4.2.5 on 2024-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_alter_item_consumable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='consumable',
            field=models.CharField(choices=[('Consumable', 'Consumable'), ('Non-Consumable', 'Non-Consumable')], max_length=20),
        ),
    ]
