# Generated by Django 4.2.5 on 2024-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_alter_item_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('Stationery', 'Stationery'), ('Decor', 'Decor'), ('Computer and Peripherals', 'Computer and Peripherals'), ('Electronics', 'Electronics'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Cleaning', 'Cleaning')], max_length=50, null=True),
        ),
    ]
