# Generated by Django 4.2.5 on 2024-01-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_itemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ItemLog',
        ),
    ]
