# Generated by Django 4.2.5 on 2024-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_logentry_delete_itemlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='log',
        ),
        migrations.AddField(
            model_name='item',
            name='logs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
