# Generated by Django 4.2.5 on 2024-01-23 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_remove_item_log_item_logs_delete_logentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='logs',
        ),
        migrations.AddField(
            model_name='item',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('office', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Assigned', 'Assigned'), ('Returned', 'Returned')], max_length=20)),
                ('office', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.item')),
            ],
        ),
    ]
