# Generated by Django 4.2.5 on 2024-01-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0128_remove_item_logs_item_log_logentry_itemlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='log',
        ),
        migrations.DeleteModel(
            name='ItemLog',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
