# Generated by Django 4.2.5 on 2024-01-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0129_remove_logentry_item_remove_item_log_delete_itemlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assignedOffice',
            field=models.TextField(blank=True),
        ),
    ]
