# Generated by Django 4.2.5 on 2024-02-08 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0132_subgroup_delete_customgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='subgroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
