# Generated by Django 4.2.5 on 2024-02-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_subgroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.subgroup'),
        ),
    ]
