# Generated by Django 4.2.5 on 2024-02-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0134_item_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubgroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_mapping', to='auth.group')),
                ('subgroups', models.ManyToManyField(to='main.subgroup')),
            ],
        ),
    ]
