# Generated by Django 4.2.5 on 2024-02-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_groupsubgroupmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsubgroupmapping',
            name='subgroups',
        ),
        migrations.AddField(
            model_name='groupsubgroupmapping',
            name='subgroup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_mapping', to='main.subgroup'),
        ),
    ]
