# Generated by Django 4.2.5 on 2024-04-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_remove_groupsubgroupmapping_subgroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('item_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='subgroup',
            name='requested_items',
            field=models.ManyToManyField(blank=True, related_name='subgroups', to='main.requestitemcount'),
        ),
    ]
