# Generated by Django 4.2.5 on 2024-04-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_requestitemcount_subgroup_requested_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgroup',
            old_name='requested_items',
            new_name='requested_item',
        ),
    ]
