# Generated by Django 4.2.5 on 2024-04-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_rename_requested_items_subgroup_requested_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgroup',
            old_name='requested_item',
            new_name='requested_items',
        ),
    ]
