# Generated by Django 4.2.5 on 2024-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_rename_requested_item_subgroup_requested_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='jinsi_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Dozen', 'Dozen'), ('Mtrs', 'Mtrs'), ('Feet', 'Feet'), ('Kilogram', 'Kilogram'), ('Liters', 'Liters'), ('Square Meter', 'Square Meter'), ('Cubic Meter', 'Cubic Meter')], max_length=50, null=True),
        ),
    ]
