# Generated by Django 4.2.5 on 2024-04-25 05:58

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_item_jinsi_no_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestitemcount',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requestitemcount',
            name='item_count',
        ),
        migrations.AddField(
            model_name='requestitemcount',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='requestitemcount',
            name='requestDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestitemcount',
            name='requestitem_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.requestitem_photo_upload_path),
        ),
        migrations.AddField(
            model_name='requestitemcount',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Dozen', 'Dozen'), ('Mtrs', 'Mtrs'), ('Feet', 'Feet'), ('Kilogram', 'Kilogram'), ('Liters', 'Liters'), ('Square Meter', 'Square Meter'), ('Cubic Meter', 'Cubic Meter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assign_item', 'Assign Item'), ('return_item', 'Return Item'), ('change_status', 'Change Status'), ('request_item', 'Request Item'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
