# Generated by Django 4.2.5 on 2024-04-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_remove_requestitemcount_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestitemcount',
            old_name='item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='requestitemcount',
            name='requestitem_photo',
        ),
    ]
