# Generated by Django 4.2.5 on 2024-04-28 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0142_rename_item_requestitemcount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitemcount',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
