# Generated by Django 4.2.5 on 2024-04-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_requestitemcount_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitemcount',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
