# Generated by Django 4.2.5 on 2024-04-28 07:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0144_requestitemcount_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitemcount',
            name='requestitem_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.requestitem_photo_upload_path),
        ),
    ]
