# Generated by Django 4.2.5 on 2024-05-21 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0147_notification_related_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentconfirmation',
            name='assigned_office',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignmentconfirmation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assign_item', 'Assign Item'), ('return_item', 'Return Item'), ('change_status', 'Change Status'), ('request_item', 'Request Item'), ('add_item', 'Add Item'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
