# Generated by Django 4.2.5 on 2024-05-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('Stationery', 'Stationery'), ('Machinery', 'Machinery'), ('ITC', 'ITC'), ('Electronics', 'Electronics'), ('Kitchen Items', 'Kitchen Items'), ('Sanitary Items', 'Sanitary Items'), ('Clothes', 'Clothes'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('none', 'None')], default='none', max_length=10, null=True),
        ),
    ]
