# Generated by Django 4.2.5 on 2024-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_alter_item_category_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_quantity', models.JSONField(default=dict)),
                ('dates', models.JSONField(default=dict)),
                ('status', models.JSONField(default=dict)),
            ],
        ),
    ]
