# Generated by Django 4.2.5 on 2024-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='requested_group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='requested_subgroup',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
