# Generated by Django 4.2.5 on 2024-05-23 16:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_itemrequest_requested_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='requestitem_photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.requestitem_photo_upload_path),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='unit',
            field=models.CharField(blank=True, choices=[('Pcs', 'Pcs'), ('Dozen', 'Dozen'), ('Mtrs', 'Mtrs'), ('Feet', 'Feet'), ('Kilogram', 'Kilogram'), ('Liters', 'Liters'), ('Square Meter', 'Square Meter'), ('Cubic Meter', 'Cubic Meter')], max_length=50, null=True),
        ),
    ]
