# Generated by Django 4.2.5 on 2024-05-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0157_alter_itemrequest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AlterField(
            model_name='assignconfirmation',
            name='assigned_to',
            field=models.CharField(max_length=255),
        ),
    ]
