# Generated by Django 4.2.5 on 2024-05-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0158_remove_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignconfirmation',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subgroup'),
        ),
    ]
