# Generated by Django 4.2.5 on 2024-05-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_alter_assignconfirmation_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignconfirmation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subgroup'),
        ),
    ]
