# Generated by Django 4.2.5 on 2024-05-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0160_alter_assignconfirmation_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='officeDate',
        ),
        migrations.AddField(
            model_name='item',
            name='assignedBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='assignedDateByGroup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='assignedDateByStore',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assign_item', 'Assign Item'), ('assign_item_store', 'Assign Item Store'), ('return_item', 'Return Item'), ('change_status', 'Change Status'), ('request_item', 'Request Item'), ('add_item', 'Add Item'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
