# Generated by Django 4.2.5 on 2024-06-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_remove_item_officedate_item_assignedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='available',
            field=models.CharField(blank=True, choices=[('Stock', 'Stock'), ('Buy', 'Buy'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='available_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
